### ISSUE TITLE
Emoji and Reactions

### ISSUE THREAD

**Issue by layiahgamer** [zackenichi/freedom-wall#7]
- Emoji
- Text and Background color changer
- Reaction to the chat option ( we can react an emoji to the message

**Comment by zackenichi** [comment]
Emoji Tool bar added in 

https://github.com/zackenichi/freedom-wall/pull/8

Working on Reaction feature next

**Comment by zackenichi** [comment]
Added reactions mechanism in pull request https://github.com/zackenichi/freedom-wall/pull/9
